### ISSUE TITLE
A test failed

### ISSUE THREAD

**Issue by louisabraham** [nmslib/hnswlib#142]
https://travis-ci.org/nmslib/hnswlib/jobs/576182855

**Comment by yurymalkov** [comment]
Thanks for reporting!

It seems that this is a bug in the test - wrong condition on data values of the return element. 
It wrongly triggers assuming the recall is exactly 1.0 (which might not be true due to stochasticity of the algorithm), while the actual recall check passes (as it allows few errors).

I'll change it so it will check only the intended functionality.

**Comment by yurymalkov** [comment]
Should be fixed now.
