### ISSUE TITLE
Cannot return the results in a contigious 2D array. Probably ef or M is too small

### ISSUE THREAD

**Issue by T-baby** [nmslib/hnswlib#244]
When I execute mark_deleted() and then execute knn_query, it reports an error, why?

I can't imagine why, thanks.

**Comment by yurymalkov** [comment]
Hi @T-baby,

This might be due to a small dataset size  ``knn_query``.  The number of return elements is less than `k`, so the algorithm assumes it cannot form a single matrix (although it is true only for non-batched searches).

This can be solved, but usually this means there is something wrong with the index or data. Maybe the dataset is too small.

This situation should be addressed in a better way though, a list can be returned instead of the matrix. I might implement another class method for that.

**Comment by T-baby** [comment]
Thank you very much, indeed the error was triggered by the value of k being greater than the actual number.
