### ISSUE TITLE
question about markdelete

### ISSUE THREAD

**Issue by Rainlolthx** [nmslib/hnswlib#275]
Thanks for this library, it works really fast. I have a question.
There is a node at level 0, and I know its id, features, and the id of all its neighbors. If I mark delete all its neighbors, can I still find it through searchKNN?

**Comment by yurymalkov** [comment]
Hi @Rainlolthx,
Thanks!
Yes, you should be able to find those elements (if you delete or update all of thier neighbors). 

Deletion is done by marking the elements. During search the algorithm still goes though those elements, but does not add them to the output. 
During updates the neighborhood elements of an update elements select new connections, so they still should be reachable (this cannot be guaranteed due to approximate nature of the algorithms)
