### ISSUE TITLE
How to clear all datas?

### ISSUE THREAD

**Issue by fgheng** [nmslib/hnswlib#347]

**Comment by yurymalkov** [comment]
You mean free memory? I guess that is `del index`

**Comment by fgheng** [comment]
> You mean free memory? I guess that is `del index`

yes, I want to delete the index and add new data to hnsw, but how do that in c++?

**Comment by yurymalkov** [comment]
It should be deallocated automatically when the class instance cease to exist (e.g. deleted or deallocated on stack)

**Comment by fgheng** [comment]
> It should be deallocated automatically when the class instance cease to exist (e.g. deleted or deallocated on stack)

thank you, I see

**Comment by kiplingw** [comment]
@yurymalkov, I see in `example_search.cpp` that the `hnswlib::HierarchicalNSW` is dynamically allocated as opposed to being constructed on the stack. If the user wishes to "reset" the index so that it is in the same "fresh" state it was in when it was first created, can this only be done by freeing the old index allocated on the heap and constructing a new one? Or can the user get by with simply calling `clear()` on an index constructed on the stack?

The reason I ask is it appears calling `clear()` leaves the index in a broken state such that subsequent calls to `addPoint()` raise a seg fault for me.

I wasn't sure if `clear()` was really not supposed to be a public interface, but just intended for the index's destructor to cleanup internal dynamic allocations.
