### ISSUE TITLE
where is the C++ implementation of this library?

### ISSUE THREAD

**Issue by siddhsql** [nmslib/hnswlib#478]
hello - noob question - where can I find the C++ implementation of this library?

**Comment by yurymalkov** [comment]
Hi @siddhsql,
This is a header-only c++ library. You can look for examples in https://github.com/nmslib/hnswlib/tree/master/examples/cpp

**Comment by siddhsql** [comment]
thanks. i am not a c++ developer. it looks like the implementation is in
the header file itself. i am not used to this pattern. could you explain me
why you put the implementation in header file itself? i didn't know this
was even possible.

**Comment by yurymalkov** [comment]
Chatgpt provided some pros and cons of header-only approach (below). The "Ease of Integration" is the main reason why I went with header-only. A header-only library can be easily converted into a standard library, so I think some of the cons can be mitigated. 

A header-only library in C++ is a library that is completely described in header files. Every part of the code, both declaration and definition, is included in the header files. This approach can have both advantages and disadvantages:

**Pros:**

- **Ease of Integration**: One of the most significant benefits is the simplicity of library integration. Users only need to include the header files in their projects without worrying about linking.
  
- **Inline Functions**: Because the code is visible, it allows for function inlining by the compiler, which can provide performance benefits.

- **Templates**: For libraries that make heavy use of templates, header-only might be the only practical option, since templates require that the entire implementation be visible at compile-time.

- **Portability**: They are highly portable, as they don't rely on pre-built binary files that need to be compatible with the user's environment (e.g., OS, architecture, compiler version, etc.).

**Cons:**

- **Compile Times**: One significant downside of header-only libraries is the potential increase in compile times, because all code is included every time the header is referenced.

- **Code Organization**: They can also make it more difficult to organize code in a clean, modular way since everything is in header files.

- **ABI Compatibility**: They have no ABI (Application Binary Interface) compatibility since every change in the library will lead to a recompilation of the dependent code.

- **Code Obfuscation**: If a library is intended to be closed-source or obfuscated, a header-only approach exposes all the code, which might not be desired.

- **Increased Binary Size**: As all the code gets included in each translation unit that includes the header, this could lead to code bloat, resulting in larger binary sizes.

- **Lack of Library Version Querying**: Unlike a compiled library, you can't query a header-only library at runtime for its version.

Deciding to use a header-only library largely depends on the nature of the project and its specific requirements. It might be a great choice for some projects and a poor choice for others.
